BEGIN;
DROP TABLE char_age;
DROP TABLE char_race;
DROP TABLE last_name;
DROP TABLE middle_name;
DROP TABLE first_name;
DROP TABLE appearances;
DROP TABLE character;
DROP TABLE rsk;
DROP TABLE race;
DROP TABLE class_skill;
DROP TABLE skill_upgrade;
DROP TABLE skill;
DROP TABLE class_upgrade;
DROP TABLE class;
DROP VIEW book_with_volume;
DROP TABLE chapter;
DROP TABLE book;
DROP TABLE volume;
COMMIT;