package org.abos.twi.knowledge.core;

import org.abos.common.Named;
import org.abos.twi.knowledge.wiki.WikiHelper;

import java.util.Objects;

public record Character(String wikiLink) implements Named {

    public static final Character ADETR = new Character(WikiHelper.WIKI_URL + "Adetr_Steelfur");
    public static final Character AIELEF = new Character(WikiHelper.WIKI_URL + "Aielef_du_Marquin");
    public static final Character ALBER = new Character(WikiHelper.WIKI_URL + "Alber");
    public static final Character ALCAZ = new Character(WikiHelper.WIKI_URL + "Alcaz");
    public static final Character ALDONSS = new Character(WikiHelper.WIKI_URL + "Aldonss");
    public static final Character ALONNA = new Character(WikiHelper.WIKI_URL + "Alonna_Swiftwing");
    public static final Character ALTESTIEL = new Character(WikiHelper.WIKI_URL + "Altestiel");
    public static final Character ANTHERR = new Character(WikiHelper.WIKI_URL + "Antherr_Twotwentyonethree_Herodotus");
    public static final Character APISTA = new Character(WikiHelper.WIKI_URL + "Apista");
    public static final Character ARTHUR = new Character(WikiHelper.WIKI_URL + "King_Arthur");
    public static final Character ASGRA = new Character(WikiHelper.WIKI_URL + "Asgra");
    public static final Character ATLANNA = new Character(WikiHelper.WIKI_URL + "Atlanna_Veltras");
    public static final Character AZKERASH = new Character(WikiHelper.WIKI_URL + "Az’kerash");
    public static final Character BADARROW = new Character(WikiHelper.WIKI_URL + "Badarrow");
    public static final Character BAMER = new Character(WikiHelper.WIKI_URL + "Bamer");
    public static final Character BEILMARK = new Character(WikiHelper.WIKI_URL + "Beilmark");
    public static final Character BELAVIERR = new Character(WikiHelper.WIKI_URL + "Belavierr_Donamia");
    public static final Character BELSC = new Character(WikiHelper.WIKI_URL + "Belsc");
    public static final Character BETHAL = new Character(WikiHelper.WIKI_URL + "Bethal_Walchaís");
    public static final Character BEZALE = new Character(WikiHelper.WIKI_URL + "Bezale");
    public static final Character BIRD = new Character(WikiHelper.WIKI_URL + "Bird");
    public static final Character BRIGANDA = new Character(WikiHelper.WIKI_URL + "Briganda_Rishaw");
    public static final Character CALESCENT = new Character(WikiHelper.WIKI_URL + "Calescent");
    public static final Character CALIFOR = new Character(WikiHelper.WIKI_URL + "Califor_Weishart");
    public static final Character CARA = new Character(WikiHelper.WIKI_URL + "Cara_O'Sullivan");
    public static final Character CHALDION = new Character(WikiHelper.WIKI_URL + "Chaldion_Oliwing");
    public static final Character COLFA = new Character(WikiHelper.WIKI_URL + "Colfa_val_Lischelle-Drakle");
    public static final Character CORETINE = new Character(WikiHelper.WIKI_URL + "Coretine");
    public static final Character CHOLE = new Character(WikiHelper.WIKI_URL + "Chole");
    public static final Character CYNTHIA = new Character(WikiHelper.WIKI_URL + "Cynthia");
    public static final Character DALIMONT = new Character(WikiHelper.WIKI_URL + "Dalimont");
    public static final Character DESKIE = new Character(WikiHelper.WIKI_URL + "Deskie");
    public static final Character DOTS = new Character(WikiHelper.WIKI_URL + "Dots");
    public static final Character DRASSI = new Character(WikiHelper.WIKI_URL + "Drassi_Tewing");
    public static final Character DULN = new Character(WikiHelper.WIKI_URL + "Duln");
    public static final Character DURENE = new Character(WikiHelper.WIKI_URL + "Durene_Faerise");
    public static final Character EDDY = new Character(WikiHelper.WIKI_URL + "Edward");
    public static final Character EKIRRA = new Character(WikiHelper.WIKI_URL + "Ekirra_Silverfang");
    public static final Character ELDAVIN = new Character(WikiHelper.WIKI_URL + "Eldavin");
    public static final Character ELIRR = new Character(WikiHelper.WIKI_URL + "Elirr_Fultpar");
    public static final Character ELOISE = new Character(WikiHelper.WIKI_URL + "Eloise_du_Havin");
    public static final Character EMILY = new Character(WikiHelper.WIKI_URL + "Emily");
    public static final Character EREK = new Character(WikiHelper.WIKI_URL + "Erek");
    public static final Character ERIN = new Character(WikiHelper.WIKI_URL + "Erin_Solstice");
    public static final Character FETOHEP = new Character(WikiHelper.WIKI_URL + "Fetohep");
    public static final Character FIERRE = new Character(WikiHelper.WIKI_URL + "Serafierre_val_Lischelle-Drakle");
    public static final Character FLOS = new Character(WikiHelper.WIKI_URL + "Flos_Reimarch");
    public static final Character FLOODED_WATERS_CHIEFTAIN = new Character(WikiHelper.WIKI_URL + "Goblin_Chieftain");
    public static final Character FLUFFLES_IV = new Character(WikiHelper.WIKI_URL + "Fluffles_IV");
    public static final Character GARIA = new Character(WikiHelper.WIKI_URL + "Garia_Strongheart");
    public static final Character GALINA = new Character(WikiHelper.WIKI_URL + "Galina");
    public static final Character GERSHAL = new Character(WikiHelper.WIKI_URL + "Gershal");
    public static final Character GEWILENA = new Character(WikiHelper.WIKI_URL + "Gewilena");
    public static final Character GRIMALKIN = new Character(WikiHelper.WIKI_URL + "Grimalkin_Duveig");
    public static final Character HALRAC = new Character(WikiHelper.WIKI_URL + "Halrac_Everam");
    public static final Character HANDYFELLOW = new Character(WikiHelper.WIKI_URL + "Handyfellow");
    public static final Character HAWK = new Character(WikiHelper.WIKI_URL + "Hawk");
    public static final Character HAYVON = new Character(WikiHelper.WIKI_URL + "Hayvon_Operland");
    public static final Character HEDAULT = new Character(WikiHelper.WIKI_URL + "Hedault");
    public static final Character HELM = new Character(WikiHelper.WIKI_URL + "Helm");
    public static final Character HEROVE = new Character(WikiHelper.WIKI_URL + "Herove_Canidus");
    public static final Character HETHON = new Character(WikiHelper.WIKI_URL + "Hethon_Veltras");
    public static final Character HEXEL = new Character(WikiHelper.WIKI_URL + "Hexel_Quithail");
    public static final Character HIMILT = new Character(WikiHelper.WIKI_URL + "Himilt_val_Lischelle-Drakle");
    public static final Character IEKA = new Character(WikiHelper.WIKI_URL + "Ieka_Imarris");
    public static final Character IELANE = new Character(WikiHelper.WIKI_URL + "Ielane_du_Marquin");
    public static final Character ILVRISS = new Character(WikiHelper.WIKI_URL + "Ilvriss_Gemscale");
    public static final Character IMANI = new Character(WikiHelper.WIKI_URL + "Imani");
    public static final Character IMOR = new Character(WikiHelper.WIKI_URL + "Imor_Seagrass");
    public static final Character INKPAPER = new Character(WikiHelper.WIKI_URL + "Inkpaper");
    public static final Character IRADOREN = new Character(WikiHelper.WIKI_URL + "Iradoren");
    public static final Character ISHKR = new Character(WikiHelper.WIKI_URL + "Ishkr_Silverfang");
    public static final Character JEISS = new Character(WikiHelper.WIKI_URL + "Jeiss_Sielmark");
    public static final Character JELAQUA = new Character(WikiHelper.WIKI_URL + "Jelaqua_Ivirith");
    public static final Character JERICHA = new Character(WikiHelper.WIKI_URL + "Jericha_Synthel");
    public static final Character JEWEL = new Character(WikiHelper.WIKI_URL + "Jewel");
    public static final Character JOSEPH = new Character(WikiHelper.WIKI_URL + "Joseph_Ortega");
    public static final Character KASIGNA = new Character(WikiHelper.WIKI_URL + "Kasigna");
    public static final Character KATY = new Character(WikiHelper.WIKI_URL + "Katy");
    public static final Character KEITH = new Character(WikiHelper.WIKI_URL + "Keith");
    public static final Character KEVIN = new Character(WikiHelper.WIKI_URL + "Kevin_Hall");
    public static final Character KHORPE = new Character(WikiHelper.WIKI_URL + "Khorpe");
    public static final Character KLBKCH = new Character(WikiHelper.WIKI_URL + "Klbkch");
    public static final Character KRSHIA = new Character(WikiHelper.WIKI_URL + "Krshia_Silverfang");
    public static final Character LACRESE = new Character(WikiHelper.WIKI_URL + "Lacrese");
    public static final Character LAKEN = new Character(WikiHelper.WIKI_URL + "Laken_Godart");
    public static final Character LEON = new Character(WikiHelper.WIKI_URL + "Leon");
    public static final Character LILY = new Character(WikiHelper.WIKI_URL + "Lillian_Woods");
    public static final Character LISKA = new Character(WikiHelper.WIKI_URL + "Liska_Silverfang");
    public static final Character LISM = new Character(WikiHelper.WIKI_URL + "Lism_Swifttail");
    public static final Character LORMEL = new Character(WikiHelper.WIKI_URL + "Lormel");
    public static final Character LYONETTE = new Character(WikiHelper.WIKI_URL + "Lyonette_du_Marquin");
    public static final Character MAGNOLIA = new Character(WikiHelper.WIKI_URL + "Magnolia_Reinhart");
    public static final Character MARAN = new Character(WikiHelper.WIKI_URL + "Maran");
    public static final Character MARIAN_US = new Character(WikiHelper.WIKI_URL + "Marian_(The_Americans)");
    public static final Character MENISI = new Character(WikiHelper.WIKI_URL + "Menisi_du_Marquin");
    public static final Character MENOLIT = new Character(WikiHelper.WIKI_URL + "Menolit");
    public static final Character MERISH = new Character(WikiHelper.WIKI_URL + "Merish");
    public static final Character MILAW = new Character(WikiHelper.WIKI_URL + "Milaw");
    public static final Character MONTRESSA = new Character(WikiHelper.WIKI_URL + "Montressa_du_Valeross");
    public static final Character MOORE = new Character(WikiHelper.WIKI_URL + "Moore_of_Raithland");
    public static final Character MRSHA = new Character(WikiHelper.WIKI_URL + "Mrsha_du_Marquin");
    public static final Character NANETTE = new Character(WikiHelper.WIKI_URL + "Nanette_Weishart");
    public static final Character NERESHAL = new Character(WikiHelper.WIKI_URL + "Nereshal");
    public static final Character NERUL = new Character(WikiHelper.WIKI_URL + "Nerul_Gemscale");
    public static final Character NIERS = new Character(WikiHelper.WIKI_URL + "Niers_Astoragon");
    public static final Character NOKHA = new Character(WikiHelper.WIKI_URL + "Nokha");
    public static final Character NORMEN = new Character(WikiHelper.WIKI_URL + "Normen_Callesn");
    public static final Character NUMBTONGUE = new Character(WikiHelper.WIKI_URL + "Numbtongue");
    public static final Character OCTAVIA = new Character(WikiHelper.WIKI_URL + "Octavia_Cotton");
    public static final Character OLIYAYA = new Character(WikiHelper.WIKI_URL + "Oliyaya");
    public static final Character ORTHENON = new Character(WikiHelper.WIKI_URL + "Orthenon");
    public static final Character OTHIUS = new Character(WikiHelper.WIKI_URL + "Othius_the_Fourth");
    public static final Character PALT = new Character(WikiHelper.WIKI_URL + "Palt_Fenrisol");
    public static final Character PEGGY = new Character(WikiHelper.WIKI_URL + "Peggy");
    public static final Character PELT = new Character(WikiHelper.WIKI_URL + "Pelt_Dooristone");
    public static final Character PICKER = new Character(WikiHelper.WIKI_URL + "Picker");
    public static final Character PISCES = new Character(WikiHelper.WIKI_URL + "Pisces_Jealnet");
    public static final Character PRHA = new Character(WikiHelper.WIKI_URL + "Prha");
    public static final Character PRYDE = new Character(WikiHelper.WIKI_URL + "Pryde_Ulta");
    public static final Character QUARASS = new Character(WikiHelper.WIKI_URL + "Quarass");
    public static final Character RAEKEA = new Character(WikiHelper.WIKI_URL + "Raekea_Silversmith");
    public static final Character RAFAEMA = new Character(WikiHelper.WIKI_URL + "Rafaema_Manusara_Coloseuvia");
    public static final Character RAGS = new Character(WikiHelper.WIKI_URL + "Rags");
    public static final Character RECLIS = new Character(WikiHelper.WIKI_URL + "Reclis_du_Marquin");
    public static final Character RED = new Character(WikiHelper.WIKI_URL + "Red");
    public static final Character RELC = new Character(WikiHelper.WIKI_URL + "Relc_Grasstongue");
    public static final Character RESK = new Character(WikiHelper.WIKI_URL + "Resk");
    public static final Character RESSGA = new Character(WikiHelper.WIKI_URL + "Ressga");
    public static final Character REVI = new Character(WikiHelper.WIKI_URL + "Revi_Cotton");
    public static final Character REYANNE = new Character(WikiHelper.WIKI_URL + "Reyanne");
    public static final Character RICHARD = new Character(WikiHelper.WIKI_URL + "Richard_Davenport");
    public static final Character RON = new Character(WikiHelper.WIKI_URL + "Ron");
    public static final Character ROSE = new Character(WikiHelper.WIKI_URL + "Rose_Cinevoy");
    public static final Character ROSENCRANTZ = new Character(WikiHelper.WIKI_URL + "Rosencrantz");
    public static final Character RYOKA = new Character(WikiHelper.WIKI_URL + "Ryoka_Griffin");
    public static final Character SAFRY = new Character(WikiHelper.WIKI_URL + "Safry");
    public static final Character SALISS = new Character(WikiHelper.WIKI_URL + "Saliss_Oliwing");
    public static final Character SALKIS = new Character(WikiHelper.WIKI_URL + "Salkis_Blackwing");
    public static final Character SAMMIAL = new Character(WikiHelper.WIKI_URL + "Sammial_Veltras");
    public static final Character SELYS = new Character(WikiHelper.WIKI_URL + "Selys_Shivertail");
    public static final Character SERAPHEL = new Character(WikiHelper.WIKI_URL + "Seraphel_du_Marquin");
    public static final Character SEST = new Character(WikiHelper.WIKI_URL + "Sest");
    public static final Character SEVE = new Character(WikiHelper.WIKI_URL + "Seve-Alrelious");
    public static final Character SHARDELE = new Character(WikiHelper.WIKI_URL + "Shardele_du_Marquin");
    public static final Character SILVERBOOTS = new Character(WikiHelper.WIKI_URL + "Silverboots");
    public static final Character SILVERMOP = new Character(WikiHelper.WIKI_URL + "Silvermop");
    public static final Character SNATCHER = new Character(WikiHelper.WIKI_URL + "Snatcher");
    public static final Character SOLTON = new Character(WikiHelper.WIKI_URL + "Solton");
    public static final Character STACY = new Character(WikiHelper.WIKI_URL + "Stacy");
    public static final Character STICK = new Character(WikiHelper.WIKI_URL + "Sticks");
    public static final Character TALETEVIRION = new Character(WikiHelper.WIKI_URL + "Taletevirion");
    public static final Character TEKSHIA = new Character(WikiHelper.WIKI_URL + "Tekshia_Shivertail");
    public static final Character TEMILE = new Character(WikiHelper.WIKI_URL + "Temile");
    public static final Character TERES = new Character(WikiHelper.WIKI_URL + "Teresa_Atwood");
    public static final Character TERIARCH = new Character(WikiHelper.WIKI_URL + "Teriarch");
    public static final Character TESSA = new Character(WikiHelper.WIKI_URL + "Tessa");
    public static final Character THUNDERFUR = new Character(WikiHelper.WIKI_URL + "Thunderfur");
    public static final Character TIMBOR = new Character(WikiHelper.WIKI_URL + "Timbor_Parithad");
    public static final Character TIGORE = new Character(WikiHelper.WIKI_URL + "Tigore");
    public static final Character TISMEL = new Character(WikiHelper.WIKI_URL + "Tismel_Lischscale");
    public static final Character TKRN = new Character(WikiHelper.WIKI_URL + "Tkrn_Silverfang");
    public static final Character TOM = new Character(WikiHelper.WIKI_URL + "Thomas_Trautmann");
    public static final Character TREY = new Character(WikiHelper.WIKI_URL + "Trey_Atwood");
    public static final Character TROYDEL = new Character(WikiHelper.WIKI_URL + "Troydel");
    public static final Character TYPHENOUS = new Character(WikiHelper.WIKI_URL + "Typhenous");
    public static final Character ULLIM = new Character(WikiHelper.WIKI_URL + "Ullim");
    public static final Character ULVAMA = new Character(WikiHelper.WIKI_URL + "Ulvama");
    public static final Character URKSH = new Character(WikiHelper.WIKI_URL + "Urksh");
    public static final Character USHAR = new Character(WikiHelper.WIKI_URL + "Ushar");
    public static final Character VALETERISA = new Character(WikiHelper.WIKI_URL + "Valeterisa_Imarris");
    public static final Character VENSHA = new Character(WikiHelper.WIKI_URL + "Vensha");
    public static final Character VERNOUE = new Character(WikiHelper.WIKI_URL + "Vernoue_du_Marquin");
    public static final Character VESS = new Character(WikiHelper.WIKI_URL + "Vess");
    public static final Character VINCENT = new Character(WikiHelper.WIKI_URL + "Vincent");
    public static final Character VISMA = new Character(WikiHelper.WIKI_URL + "Visma");
    public static final Character WAILANT = new Character(WikiHelper.WIKI_URL + "Wailant_Strongheart");
    public static final Character XARKOUTH = new Character(WikiHelper.WIKI_URL + "Xarkouth");
    public static final Character XHERW = new Character(WikiHelper.WIKI_URL + "Xherw");
    public static final Character YELROAN = new Character(WikiHelper.WIKI_URL + "Yelroan");
    public static final Character YESNE = new Character(WikiHelper.WIKI_URL + "Yesne");
    public static final Character ZALAISS = new Character(WikiHelper.WIKI_URL + "Zalaiss_Holmfyre");
    public static final Character ZEL = new Character(WikiHelper.WIKI_URL + "Zel_Shivertail");
    public static final Character ZEVARA = new Character(WikiHelper.WIKI_URL + "Zevara_Sunderscale");

    public Character(final String wikiLink) {
        this.wikiLink = Objects.requireNonNull(wikiLink);
    }

    @Override
    public String getName() {
        final int index = wikiLink.substring(0, wikiLink.length()-1).lastIndexOf('/');
        if (index == -1) {
            return wikiLink.replace('_', ' ').replace("/", "");
        }
        return wikiLink.substring(index+1).replace('_', ' ').replace("/", "");
    }
}
